# Generated by Django 5.1.7 on 2025-03-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
