# Generated by Django 5.1.7 on 2025-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Postponed', 'Postponed')], default='Pending', max_length=20),
        ),
    ]
