# Generated by Django 5.1.7 on 2025-03-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_remove_task_assigned_to_remove_task_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Myapp.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=255),
        ),
        migrations.DeleteModel(
            name='TaskResponse',
        ),
    ]
