# Generated by Django 5.1.7 on 2025-03-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_alter_taskstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Postponed', 'Postponed')], max_length=10),
        ),
    ]
