# Generated by Django 5.1.7 on 2025-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_task_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='finesh',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Postponed', 'Postponed'), ('Complete', 'complete'), ('InComplete', 'inComplete')], default='Incomplete', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Postponed', 'Postponed'), ('Complete', 'complete'), ('InComplete', 'inComplete')], max_length=10),
        ),
    ]
