# Generated by Django 5.1.7 on 2025-03-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_alter_taskstatus_finesh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='finesh',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='completion_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Postponed', 'Postponed')], default='Pending', max_length=15),
        ),
    ]
