# Generated by Django 5.1.7 on 2025-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_remove_taskstatus_due_date_remove_taskstatus_finesh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Postponed', 'Postponed')], max_length=10),
        ),
    ]
