# Generated by Django 5.1.7 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0024_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='completion_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('InProgress', 'InProgress')], default='InProgress', max_length=15),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Postponed', 'Postponed')], default='Postponed', max_length=10),
        ),
    ]
