# Generated by Django 5.1.7 on 2025-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0026_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
