# Generated by Django 5.1.7 on 2025-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0027_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
