# Generated by Django 5.1.7 on 2025-03-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0028_task_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_completed',
        ),
    ]
