# Generated by Django 5.1.7 on 2025-03-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_remove_task_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('early', 'Completed Early'), ('ontime', 'Completed On Time'), ('late', 'Completed Late')], max_length=10)),
                ('days_difference', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.employee')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='Myapp.task')),
            ],
            options={
                'verbose_name': 'Task Completion',
                'verbose_name_plural': 'Task Completions',
            },
        ),
    ]
