# Generated by Django 5.1.7 on 2025-03-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0030_taskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='Myapp.task'),
        ),
    ]
