# Generated by Django 5.1.7 on 2025-03-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0033_alter_taskcompletion_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Postponed', 'Postponed'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Postponed', 'Postponed'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('completion_type', models.CharField(blank=True, choices=[('early', 'Completed Early'), ('ontime', 'Completed On Time'), ('late', 'Completed Late')], max_length=10, null=True)),
                ('days_difference', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='Myapp.employee')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='Myapp.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskCompletion',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
