# Generated by Django 5.1.7 on 2025-03-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0034_remove_taskstatus_employee_remove_taskstatus_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='Myapp.task'),
        ),
    ]
