# Generated by Django 5.1.7 on 2025-03-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0044_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
    ]
