# Generated by Django 5.1.7 on 2025-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0047_alter_taskprogress_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
