# Generated by Django 5.1.7 on 2025-04-01 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0052_alter_taskprogress_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
