# Generated by Django 5.1.7 on 2025-04-01 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0053_alter_taskprogress_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='action_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
