# Generated by Django 5.1.7 on 2025-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0055_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
    ]
