# Generated by Django 5.1.7 on 2025-04-02 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0056_alter_taskprogress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
