# Generated by Django 5.2 on 2025-04-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0058_basecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecompany',
            name='created_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to='Myapp.hr'),
        ),
    ]
