# Generated by Django 5.2 on 2025-04-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0059_alter_basecompany_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to='Myapp.hr'),
        ),
        migrations.DeleteModel(
            name='BaseCompany',
        ),
    ]
