# Generated by Django 5.2 on 2025-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0061_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
