# Generated by Django 5.2 on 2025-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0067_employee_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leves',
            field=models.IntegerField(default=0),
        ),
    ]
