# Generated by Django 5.2 on 2025-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0070_alter_employee_logedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
