# Generated by Django 5.2 on 2025-04-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0071_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True, max_length=175, null=True),
        ),
    ]
