# Generated by Django 5.2 on 2025-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0072_employee_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
