# Generated by Django 5.2 on 2025-04-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0074_workleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='Myapp.employee'),
        ),
    ]
