# Generated by Django 5.2 on 2025-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0075_alter_workleave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
