# Generated by Django 5.2 on 2025-05-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0076_alter_taskprogress_completion_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HR',
            new_name='TeamLead',
        ),
    ]
