# Generated by Django 5.2 on 2025-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0077_rename_hr_teamlead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='leves',
            new_name='leave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='logedin',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('HR', 'Human Resources'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Support', 'Customer Support'), ('Finance', 'Finance')], default='General', max_length=50),
        ),
    ]
