# Generated by Django 5.2 on 2025-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0080_alter_employee_department_alter_teamlead_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Undisclosed', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Undisclosed', max_length=10, null=True),
        ),
    ]
