# Generated by Django 5.2 on 2025-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0084_alter_employee_status_alter_teamlead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('onleave', 'On Leave'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='inactive', max_length=20),
        ),
    ]
