# Generated by Django 5.2 on 2025-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0085_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('onleave', 'On Leave'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('onleave', 'On Leave'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='Inactive', max_length=20),
        ),
    ]
