# Generated by Django 5.2 on 2025-05-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0086_alter_employee_status_alter_teamlead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teamlead',
            name='status',
        ),
    ]
