# Generated by Django 5.2 on 2025-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0088_employee_status_teamlead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
    ]
