# Generated by Django 5.2 on 2025-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0090_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workleave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'sick'), ('Casual Leave', 'casual'), ('Earned Leave', 'earned'), ('Unpaid Leave', 'unpaid')], max_length=50),
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
