# Generated by Django 5.2 on 2025-05-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0091_workleave_is_responded_alter_workleave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
