# Generated by Django 5.2 on 2025-05-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0092_workleave_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_notes', to='Myapp.teamlead')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Myapp.workleave')),
            ],
        ),
    ]
