# Generated by Django 5.2 on 2025-05-09 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0093_leavenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='Myapp.teamlead'),
        ),
        migrations.AddField(
            model_name='workleave',
            name='leave_balance',
            field=models.IntegerField(blank=True, help_text='Remaining leave balance (max 20)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='workleave',
            name='modified_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='modified_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LeaveNote',
        ),
    ]
