# Generated by Django 5.2 on 2025-05-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0094_workleave_approved_by_workleave_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workleave',
            name='is_reconsidered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workleave',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='reconsider_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='reconsidered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('reconsidered', 'Reconsidered')], default='pending', max_length=20),
        ),
    ]
