# Generated by Django 5.2 on 2025-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0095_workleave_duration_workleave_is_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected'), ('Modified', 'modified'), ('Reconsidered', 'reconsidered')], default='pending', max_length=20),
        ),
    ]
