# Generated by Django 5.2 on 2025-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0096_alter_workleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('reconsidered', 'Reconsidered')], default='pending', max_length=20),
        ),
    ]
