# Generated by Django 5.2 on 2025-05-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0098_alter_workleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='modified_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
