# Generated by Django 5.2 on 2025-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0099_workleave_modified_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='modification_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
