# Generated by Django 5.2 on 2025-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0100_workleave_modification_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'sick'), ('Casual Leave', 'casual'), ('Earned Leave', 'earned'), ('Unpaid Leave', 'unpaid'), ('Emergency Leave', 'emergeancy')], max_length=50),
        ),
    ]
