# Generated by Django 5.2 on 2025-05-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0104_alter_workleave_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
