# Generated by Django 5.2 on 2025-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0105_alter_workleave_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'sick'), ('Casual Leave', 'casual'), ('Vacation Leave', 'vacation'), ('Earned Leave', 'earned'), ('Unpaid Leave', 'unpaid'), ('Emergency Leave', 'emergency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Draft', 'draft'), ('Approved', 'approved'), ('Rejected', 'rejected'), ('Modified', 'modified'), ('Reconsidered', 'reconsidered')], default='pending', max_length=20),
        ),
    ]
