# Generated by Django 5.2 on 2025-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0106_alter_workleave_leave_type_alter_workleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='contactInfo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='delegate_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workleave',
            name='notify_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workleave',
            name='out_of_office',
            field=models.BooleanField(default=False),
        ),
    ]
