# Generated by Django 5.2 on 2025-05-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0107_workleave_contactinfo_workleave_delegate_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workleave',
            old_name='contactInfo',
            new_name='contact_info',
        ),
    ]
