# Generated by Django 5.2 on 2025-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0108_rename_contactinfo_workleave_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='contact_info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
