# Generated by Django 5.2 on 2025-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0109_alter_workleave_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='workleave',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
