# Generated by Django 5.2 on 2025-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0111_workleave_half_day_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
