# Generated by Django 5.2 on 2025-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0112_alter_workleave_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workleave',
            old_name='reason',
            new_name='reason_discription',
        ),
        migrations.AddField(
            model_name='workleave',
            name='reason_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
