# Generated by Django 5.2 on 2025-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0113_rename_reason_workleave_reason_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='reason_title',
            field=models.TextField(),
        ),
    ]
