# Generated by Django 5.2 on 2025-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0114_alter_workleave_reason_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workleave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'sick'), ('Casual Leave', 'casual'), ('Vacation Leave', 'vacation'), ('Earned Leave', 'earned'), ('Unpaid Leave', 'unpaid'), ('Emergency Leave', 'emergency')], default='Earned Leave', max_length=50),
        ),
        migrations.AlterField(
            model_name='workleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Modified', 'Modified'), ('Reconsidered', 'Reconsidered'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
