# Generated by Django 5.2 on 2025-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0115_alter_workleave_leave_type_alter_workleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_days_to_work',
            field=models.IntegerField(default=30),
        ),
    ]
