# Generated by Django 5.2 on 2025-06-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0116_company_total_days_to_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
