# Generated by Django 5.2 on 2025-06-09 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0117_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='allow_custom_themes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_resume_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='company_brochures/'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='data_retention_period',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='company',
            name='founding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_mode',
            field=models.CharField(choices=[('Video', 'Video'), ('In-Person', 'In-Person'), ('Hybrid', 'Hybrid')], default='Video', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='privacy_policy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='task_limit_per_day',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_of_service_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='test_difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='working_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.CharField(default='9:00 AM - 6:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
