# Generated by Django 5.2 on 2025-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0121_remove_employee_skills_education_experience_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='total_days_to_work',
            field=models.IntegerField(default=100),
        ),
    ]
