# Generated by Django 5.2 on 2025-06-17 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0122_alter_company_total_days_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Undisclosed', 'Undisclosed')], default='Undisclosed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Undisclosed', 'Undisclosed')], default='Undisclosed', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='hr_profiles/')),
                ('hr_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Undisclosed', 'Undisclosed')], default='Undisclosed', max_length=20, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onleave', 'On Leave'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='Inactive', max_length=20)),
                ('about', models.TextField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_users', to='Myapp.company')),
            ],
        ),
    ]
