# Generated by Django 5.2 on 2025-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0125_rename_contact_number_hr_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
