# Generated by Django 5.2 on 2025-06-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0126_hr_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
