# Generated by Django 5.2 on 2025-06-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0128_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hr',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
