# Generated by Django 5.2 on 2025-06-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0129_hr_address_hr_days_worked_hr_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='slogan',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
