# Generated by Django 5.2 on 2025-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0130_hr_leave_team_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='hr',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive'), ('Terminated', 'Terminated')], default='Inactive', max_length=20),
        ),
    ]
