# Generated by Django 5.2 on 2025-06-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0131_alter_employee_status_alter_hr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_users', to='Myapp.company'),
        ),
    ]
