# Generated by Django 5.2 on 2025-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0132_teamlead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
