# Generated by Django 5.2 on 2025-06-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0133_alter_teamlead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='teamLead_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
