# Generated by Django 5.2 on 2025-06-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0134_alter_teamlead_teamlead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Curricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Myapp.hr')),
            ],
        ),
    ]
