# Generated by Django 5.2 on 2025-06-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0136_education_content_type_education_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='education',
            name='object_id',
        ),
    ]
