# Generated by Django 5.2 on 2025-06-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0137_remove_education_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_curricular',
            name='Hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Myapp.teamlead'),
        ),
    ]
