# Generated by Django 5.2 on 2025-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0139_co_curricular_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_curricular',
            name='proficiency',
            field=models.IntegerField(max_length=5),
        ),
    ]
