# Generated by Django 5.2 on 2025-07-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0141_alter_co_curricular_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
