# Generated by Django 5.2 on 2025-07-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0142_hr_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='persional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
