# Generated by Django 5.2 on 2025-07-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0143_teamlead_persional_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='persional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
