# Generated by Django 5.2 on 2025-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0144_employee_persional_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
