# Generated by Django 5.2 on 2025-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0145_teamlead_city_teamlead_postal_code_teamlead_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
