# Generated by Django 5.2 on 2025-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0146_teamlead_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
