# Generated by Django 5.2 on 2025-07-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0147_teamlead_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamlead',
            old_name='two_factor_enabled',
            new_name='enable_two_factor',
        ),
    ]
