# Generated by Django 5.2 on 2025-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0148_rename_two_factor_enabled_teamlead_enable_two_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='enable_two_factor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
