# Generated by Django 5.2 on 2025-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0151_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='device_info',
            field=models.CharField(blank=True, null=True),
        ),
    ]
