# Generated by Django 5.2 on 2025-07-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0152_loginhistory_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
