# Generated by Django 5.2 on 2025-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0153_loginhistory_browser_alter_loginhistory_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='is_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
