# Generated by Django 5.2 on 2025-07-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0156_co_curricular_content_type_co_curricular_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='employee',
        ),
    ]
