# Generated by Django 5.2 on 2025-07-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0158_remove_education_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co_curricular',
            name='Hr',
        ),
    ]
