# Generated by Django 5.2 on 2025-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0159_remove_co_curricular_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school_10_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_12_year',
        ),
        migrations.AddField(
            model_name='education',
            name='school_10_year_end',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_10_year_start',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_12_year_end',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_12_year_start',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
