# Generated by Django 5.2 on 2025-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0160_remove_education_school_10_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='co_curricular',
            name='discription',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='co_curricular',
            name='proficiency',
            field=models.IntegerField(max_length=100),
        ),
    ]
