# Generated by Django 5.2 on 2025-07-13 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0162_alter_co_curricular_proficiency'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_curricular',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Certficate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('file', models.ImageField(upload_to='Certificates/')),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
