# Generated by Django 5.2 on 2025-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0164_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certficate',
            name='file',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
