# Generated by Django 5.2 on 2025-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0165_alter_certficate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
