# Generated by Django 5.2 on 2025-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0168_alter_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.FloatField(default=2.5),
        ),
    ]
