# Generated by Django 5.2 on 2025-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0172_alter_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_curricular',
            name='proficiency',
            field=models.FloatField(default=5),
        ),
    ]
