# Generated by Django 5.2 on 2025-07-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0173_alter_co_curricular_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='level_of_basic_setting_set',
            field=models.IntegerField(default=0),
        ),
    ]
